### ISSUE TITLE
Emblem configuration

### ISSUE THREAD

**Issue by iamdtang** [suchitadoshi1987/related-files-hopper#11]
What configuration would I need for an Ember project where all of the templates are `.emblem` instead of `.hbs`?

**Comment by suchitadoshi1987** [comment]
@skaterdav85 you can add `emblem` as one of the supported extension in the `fileHopper.supportedExtensions` array in your `settings.json` and if you want the label to work for `emblem` files, you could add your own custom `labelRuleSet`, something like:
```
"fileHopper.labelRuleSets": [
    {
      "folderName": "",
      "title": "Component Template",
      "regexPatterns": ["(.+).emblem"]
    },
]
```
or something like that

**Comment by iamdtang** [comment]
hmm, ok, I added `"fileHopper.supportedExtensions": ["emblem"],` to `settings.json` and for one of my `.emblem` component templates, I did `Cmd+Shift+.` and it says No related files found.

**Comment by suchitadoshi1987** [comment]
`"fileHopper.supportedExtensions": ["emblem"]` this alone won't help, this means that the only extension that the file hopper should look for is `.emblem`. You would need to do something like:
```
"fileHopper.supportedExtensions": [
            "emblem", 
             "js",
            "ts",
            "html",
            "hbs",
            "css",
            "scss"
]
```
or whatever are the possible extensions that your app supports

**Comment by iamdtang** [comment]
Thanks!
