### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by boris-petrov** [suchitadoshi1987/related-files-hopper#12]
I have a `frontend` folder in my root workspace dir which contains an Ember app. So inside this `frontend` folder there is an `app` folder with all the Ember stuff in it.

This is the config I use:

```json
    "fileHopper.appRootFolders": ["frontend/app"],
    "fileHopper.labelRuleSets": [
        {
            "folderName": "components",
            "title": "Component",
            "regexPatterns": ["(.+)\\.(coffee|ts)"],
        },
        {
            "folderName": "components",
            "title": "Component Template",
            "regexPatterns": ["(.+)\\.hbs"],
        },
        {
            "folderName": "templates",
            "title": "Component Template",
            "regexPatterns": ["(.+)\\.hbs"],
        },
        {
            "folderName": "styles",
            "title": "Component Style",
            "regexPatterns": ["(.+)\\.scss"],
        },
    ],
```

And when I hit `CTRL+/` I get:

```
[exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
	at validateString (internal/validators.js:107:11)
	at Object.join (path.js:1037:7)
	at showRelated (/home/boris/.vscode-oss/extensions/suchitadoshi1987.file-hopper-0.3.0/extension.js:176:32)
	...
```

I tried debugging and figuring out what I do wrong but to no avail.

**Comment by suchitadoshi1987** [comment]
@boris-petrov , could you provide with the repo link for me to repro the issue? If not, could you provide with a snapshot of your project structure as well as the file path on which this error occurred.

Thanks.

**Comment by boris-petrov** [comment]
@suchitadoshi1987 - thanks for the support!

[Here is a repo](https://github.com/boris-petrov/related-files-hopper-bug). Open the *main* directory (not `frontend`) in VSCode, then open the `foo-component.js` file and press `CTRL+/`. It blows up.

**Comment by suchitadoshi1987** [comment]
@boris-petrov , try removing the ` "fileHopper.appRootFolders": ["frontend/app"],` from your `settings.json`. Since your project structure already follows Ember's convention, you shouldn't need to add your own config for the root folder.

**Comment by boris-petrov** [comment]
@suchitadoshi1987 - that "fixes" the error, yes, but I don't get any related files. Not sure what I'm doing wrong... does it work on your side?

**Comment by suchitadoshi1987** [comment]
Interesting, yes, I does work for me for the repo you provided. 
<img width="1092" alt="Screen Shot 2020-01-26 at 12 35 48 PM" src="https://user-images.githubusercontent.com/1471425/73141408-7300cd00-4038-11ea-936a-5de0f063dbc6.png">

**Comment by boris-petrov** [comment]
Do you have some global configuration that could matter?

**Comment by suchitadoshi1987** [comment]
@boris-petrov could you provide me with the whole project structure that you are working with?

**Comment by suchitadoshi1987** [comment]
also, I am assuming you reloaded the window after changing the settings

**Comment by boris-petrov** [comment]
On this exact project that I gave you, I'm not getting any related files. The only "global" setting for `related-files-hopper` is `"fileHopper.supportedExtensions": ["js", "ts", "coffee", "html", "hbs", "css", "scss"],`. The rest are the local ones in the repo.

Yes, I restart VSCode when I change settings, I don't know how else to "reload".

Any ideas how to debug this? Putting `console.log` statements in the extension's code doesn't seem to help - they are not shown anywhere.

**Comment by suchitadoshi1987** [comment]
it's fairly simple to debug. Happy to help you with the walkthrough over discord

**Comment by boris-petrov** [comment]
@suchitadoshi1987 - great, we can do that tomorrow. In Ember's one? Ping me, my username is `boris` there.

**Comment by suchitadoshi1987** [comment]
@boris-petrov Pinged you

**Comment by suchitadoshi1987** [comment]
@boris-petrov I have fixed the issue with https://github.com/suchitadoshi1987/related-files-hopper/pull/13 Please confirm if it is working for you now. the version should be `0.3.1`

**Comment by boris-petrov** [comment]
@suchitadoshi1987 - works like a charm, thank you for the support!

**Comment by azhiv** [comment]
Hi there, I get the same error on MacOS with the following file structure:
`workspace/my-addon/addon/components/comp.ts`
`workspace/my-addon/addon/components/comp.hbs`
`workspace/main-app/...`

File hopper works perfectly for files in `main-app`. But for files from my-addon it crashes with the above mentioned error.
I debugged the extension a little bit and found that setting `appRootFolders` to `['addon', 'app']` seems to **fix the error**.
However, the error may occur again at some point because you pass  `rootLevelPrefixRegexString = null` to `path.join` at line
https://github.com/suchitadoshi1987/related-files-hopper/blob/e11e841811fcdccae903e8638d4a65969ec266d1/extension.js#L182

It looks like the function doesn't accept nulls and crashes. Please, consider altering the logic)
